cache: yarn

language: node_js

node_js:
  - "6"
  - "7"
  - "8"

branches:
  only:
    - master
    - dev
    - minor
    - /^greenkeeper.*$/

script:
  - yarn run lint
  - yarn run typecheck
  - yarn run test:ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
